version: '3.4'

services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
      - 9229:9229
    # command: ["nodemon", "--watch '*.ts'", '--exec "ts-node"', "--inspect=0.0.0.0:9229", "index.ts"]
    command: "nodemon --watch '*.ts' --exec \"ts-node\" index.ts"

  broker:
    image: eclipse-mosquitto
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 0.0.0.0:1883:1883
      - 0.0.0.0:9001:9001
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
      - ./broker/passwd_file:/etc/mosquitto/passwd
  
  esp_replicator:
    build: ./esp_replicator
    environment:
      NODE_ENV: development
    volumes:
      - ./esp_replicator:/app
    ports:
      - 3001:3000
      - 9228:9229
    volumes:
      - "./esp_replicator:/app"
    # command: ["nodemon", "--watch '*.ts'", '--exec "ts-node"', "--inspect=0.0.0.0:9229", "esp.ts"]
    command: "nodemon --watch '*.ts' --exec \"ts-node\" esp.ts"
  
  # db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb:/data/db
  #     - mongodb_config:/data/configdb

# volumes:
#   mongodb:
#   mongodb_config:
